version: '3.8'
services:
  app:
    build: .
    container_name: laravel_11_vue_inertia_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - laravel_network
    depends_on:
      - db
    ports:
      - "5174:5174"

  webserver:
    image: nginx:latest
    container_name: laravel_11_vue_inertia_nginx
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: laravel_11_vue_inertia_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_11_vue_inertia_phpmyadmin
    restart: unless-stopped
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
    networks:
      - laravel_network

  adminer:
      image: adminer
      container_name: laravel_11_vue_inertia_adminer
      restart: unless-stopped
      ports:
          - "8088:8080"
      environment:
          ADMINER_DEFAULT_SERVER: db
      networks:
          - laravel_network

networks:
  laravel_network:

volumes:
  dbdata:
